# Generated by Django 4.2.30 on 2026-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='QI Manager', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/company/')),
                ('address', models.TextField(blank=True, default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=10)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol (e.g., $, €, £)', max_length=5)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone (e.g., UTC, America/New_York, Europe/London)', max_length=50)),
                ('date_format', models.CharField(default='Y-m-d', help_text='Date format (e.g., Y-m-d, d/m/Y, m/d/Y)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server host', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (e.g., 587 for TLS)')),
                ('smtp_username', models.EmailField(default='', help_text='SMTP login username (email address)', max_length=254)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='SMTP login password or app password', max_length=500)),
                ('encryption_type', models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL'), ('None', 'None')], default='TLS', help_text='Connection encryption type', max_length=10)),
                ('default_sender_name', models.CharField(blank=True, default='', help_text='Default sender display name', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS for email connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('quotation', 'Quotation Email'), ('invoice', 'Invoice Email'), ('payment_receipt', 'Payment Receipt Email'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset Email'), ('reminder', 'Reminder Email')], help_text='Type of email template', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('body', models.TextField(help_text='Email body content. Use template variables below.')),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text='Available variables: client_name, invoice_number, quotation_number, due_amount, company_name, signature')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_format', models.CharField(default='INV-{YYYY}-{序号}', help_text='Invoice number format. Use {YYYY} for year, {MM} for month, {DD} for day, {序号} for sequential number. Example: INV-{YYYY}-{序号}', max_length=100)),
                ('seal_upload', models.ImageField(blank=True, help_text='Company seal/logo to appear on invoices', null=True, upload_to='settings/invoices/')),
                ('signature_upload', models.ImageField(blank=True, help_text='Authorized signature image', null=True, upload_to='settings/invoices/')),
                ('footer_text', models.TextField(blank=True, default='', help_text='Footer text to display on all invoices')),
                ('payment_instructions', models.TextField(blank=True, default='', help_text='Payment instructions shown on invoice')),
                ('due_days', models.PositiveIntegerField(default=30, help_text='Default payment due in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Configuration',
                'verbose_name_plural': 'Invoice Configuration',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method display name', max_length=100)),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], help_text='Type of payment method', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the payment method')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Payment method specific details (e.g., bank name, account number - stored encrypted in production)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment term name (e.g., Net 30, Due on Receipt)', max_length=100)),
                ('days', models.PositiveIntegerField(default=0, help_text='Number of days for payment')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the payment term')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment term is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment term')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_format', models.CharField(default='Q-{YYYY}-{序号}', help_text='Quotation number format. Use {YYYY} for year, {MM} for month, {DD} for day, {序号} for sequential number. Example: Q-{YYYY}-{序号}', max_length=100)),
                ('footer_left_content', models.TextField(blank=True, default='', help_text='Content displayed on the left side of quotation footer')),
                ('footer_right_content', models.TextField(blank=True, default='', help_text='Content displayed on the right side of quotation footer')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Common terms and conditions to include on quotations')),
                ('default_warranty', models.CharField(blank=True, default='', help_text='Default warranty text for quotations', max_length=500)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax rate percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('tax_name', models.CharField(default='VAT', help_text='Name of the tax (e.g., VAT, GST, Sales Tax)', max_length=100)),
                ('include_tax_in_total', models.BooleanField(default=True, help_text='Whether to include tax in total amount calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quotation Configuration',
                'verbose_name_plural': 'Quotation Configuration',
            },
        ),
    ]
