# Generated by Django 6.0.5 on 2026-05-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_clientcontactperson_deleted_at_and_more"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quotation_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted to Invoice"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("terms_conditions", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="clients.client",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="clients.clientcontactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("email_sent", "Email Sent"),
                            ("status_change", "Status Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation History",
                "verbose_name_plural": "Quotation Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotations.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Item",
                "verbose_name_plural": "Quotation Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["quotation_number"], name="idx_quotation_number"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["client_id"], name="idx_quotation_client"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status"], name="idx_quotation_status"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["is_deleted"], name="idx_quotation_deleted"),
        ),
        migrations.AddIndex(
            model_name="quotationhistory",
            index=models.Index(
                fields=["quotation_id"], name="idx_quotationhistory_quotation"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationhistory",
            index=models.Index(fields=["action"], name="idx_quotationhistory_action"),
        ),
        migrations.AddIndex(
            model_name="quotationhistory",
            index=models.Index(
                fields=["timestamp"], name="idx_quotationhistory_timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationitem",
            index=models.Index(
                fields=["quotation_id"], name="idx_quotationitem_quotation"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationitem",
            index=models.Index(fields=["product_id"], name="idx_quotationitem_product"),
        ),
    ]
